Repository oda-hub/dispatcher-app, pull requests merged in 2021-11, with the labels that each got.

#269 hotfix-259 - safe creation of temp dir
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/pytest_fixtures.py
  tests/test_server_basic.py
Labels: bug, multi-process

#263 Hotfix 262 - `inspect_state` functionality
  cdci_data_analysis/analysis/exceptions.py
  cdci_data_analysis/analysis/job_manager.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/pytest_fixtures.py
  tests/test_job_management.py
Labels: enhancement, hotfix

#266 selected catalog returned when loaded with file
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/plugins/dummy_instrument/empty_async_instrument.py
  cdci_data_analysis/pytest_fixtures.py
  pytest.ini
  tests/test_job_management.py
  tests/test_server_basic.py
Labels: bug, high priority

#270 Long api code attached email
  cdci_data_analysis/analysis/email_helper.py
  cdci_data_analysis/flask_app/templates/email.html
  tests/reference_emails/api_code_attachment_submitted
  tests/reference_emails/submitted-no-api-code.html
  tests/reference_emails/submitted-numeric-not-very-long-no-api-code.html
  tests/test_job_management.py
  tests/test_server_basic.py
Labels: enhancement, high priority

#264 additional message in case of connection issues
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/queries.py
  cdci_data_analysis/flask_app/dispatcher_query.py
Labels: enhancement

#272 More info connection issue
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/queries.py
Labels: enhancement

#254 default conversion for time, default t_format, some test adaption
  .gitignore
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/parameters.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  tests/reference_emails/api_code_attachment_submitted
  tests/reference_emails/submitted-dummy.html
  tests/reference_emails/submitted-numeric-not-very-long-numerical.html
  tests/test_job_management.py
  tests/test_server_basic.py
Labels: enhancement

#290 url expiration time in email template
  cdci_data_analysis/flask_app/templates/email.html
  tests/reference_emails/submitted-numeric-very-long-not-permanent.html
  tests/test_job_management.py
Labels: enhancement

#294 Limited and restricted plugin test with current app
  .github/workflows/python-plugins.yml
  cdci_data_analysis/pkg_info.json
  requirements.txt
Labels: test-plugins
