Repository oda-hub/dispatcher-app, pull requests merged in 2021-08, with the labels that each got.

#214 Test empty image
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/plugins/dummy_instrument/data_server_dispatcher.py
  tests/test_server_basic.py
Labels: enhancement, help wanted

#215 Update token email options
  cdci_data_analysis/analysis/email_helper.py
  cdci_data_analysis/analysis/hash.py
  cdci_data_analysis/analysis/tokenHelper.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/flask_app/schemas.py
  requirements.txt
  tests/test_server_basic.py
Labels: enhancement

#217 Performance
  cdci_data_analysis/analysis/products.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/flask_app/logstash.py
Labels: bug

#223 `use_scws` parameter reinserted for frontend
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/plugins/dummy_instrument/empty_async_instrument.py
  cdci_data_analysis/pytest_fixtures.py
  tests/test_job_management.py
Labels: bug
