Repository oda-hub/dispatcher-app, pull requests merged in 2022-01, with the labels that each got.

#277 posting result execution to the product gallery
  .github/workflows/python-app.yml
  .gitignore
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/analysis/email_helper.py
  cdci_data_analysis/config_dir/conf_env.yml.example
  cdci_data_analysis/configurer.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/templates/body_article_product_gallery.py
  cdci_data_analysis/pytest_fixtures.py
  pytest.ini
  requirements.txt
  tests/test_server_basic.py
Labels: enhancement, product-gallery

#316 additional log
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/pytest_fixtures.py
  tests/conftest.py
  tests/test_server_basic.py
Labels: enhancement

#321 hide gallery secret key
  cdci_data_analysis/flask_app/app.py
Labels: bug, vulnerability

#320 dedicated function for request to the gallery and additional error log
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/flask_app/app.py
Labels: product-gallery

#325 multiple retries of the request for connection issues
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/pytest_fixtures.py
Labels: bug

#336 support for different units
  .github/workflows/python-oda-api.yml
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/parameters.py
  cdci_data_analysis/plugins/dummy_instrument/empty_instrument.py
  tests/test_server_basic.py
  tests/test_unit.py
Labels: bug, test-plugins
