Repository oda-hub/dispatcher-app, pull requests merged in 2022-08, with the labels that each got.

#422 The region file is shown with the onload syntax in js9
  cdci_data_analysis/analysis/plot_tools.py
Labels: bug, test-plugins, test-oda-api

#423 Fix querying observations by timerange
  cdci_data_analysis/analysis/drupal_helper.py
  tests/test_server_basic.py
Labels: product-gallery

#427 using captureMessage Sentry client from Flask library
  cdci_data_analysis/flask_app/app.py
Labels: bug, test-plugins, test-oda-api

#431 we-are-not-sorry
  cdci_data_analysis/analysis/email_helper.py
  tests/reference_emails/done-failing.html
Labels: test-plugins, test-oda-api

#434 Hotfix manydone
  cdci_data_analysis/analysis/email_helper.py
Labels: test-plugins, test-oda-api

#435 using sentry-sdk, init and capture message, removing raven
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/analysis/email_helper.py
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/products.py
  cdci_data_analysis/analysis/queries.py
  cdci_data_analysis/analysis/renku_helper.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/plugins/dummy_instrument/data_server_dispatcher.py
  cdci_data_analysis/pytest_fixtures.py
  requirements.txt
  tests/conftest.py
  tests/test_job_management.py
Labels: bug, enhancement, test-plugins, test-oda-api

#411 Update parameters.py
  cdci_data_analysis/analysis/parameters.py
Labels: test-plugins, test-oda-api

#439 some excessive errors
  cdci_data_analysis/analysis/parameters.py
  cdci_data_analysis/analysis/products.py
  cdci_data_analysis/configurer.py
  pyproject.toml
Labels: test-plugins, test-oda-api

#446 constrain oda-api version
  setup.py
Labels: test-plugins, test-oda-api

#448 Werkzeug fix
  .bumpversion.cfg
  .github/workflows/python-plugins.yml
  cdci_data_analysis/pkg_info.json
  setup.py
Labels: test-plugins, test-oda-api

#447 refresh token endpoint
  cdci_data_analysis/analysis/exceptions.py
  cdci_data_analysis/analysis/tokenHelper.py
  cdci_data_analysis/config_dir/conf_env.yml.example
  cdci_data_analysis/configurer.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/pytest_fixtures.py
  tests/test_server_basic.py
Labels: test-plugins, test-oda-api
