Repository oda-hub/dispatcher-app, pull requests merged in 2023-01, with the labels that each got.

#504 Development instrument list
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/queries.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/plugins/dummy_plugin/dummy_plugin_conf.yml
  cdci_data_analysis/plugins/dummy_plugin/empty_development_instrument.py
  cdci_data_analysis/plugins/dummy_plugin/exposer.py
  tests/test_server_basic.py
Labels: enhancement, test-plugins, test-oda-api

#493 Parameter restrictions in metadata
  .github/workflows/python-plugins.yml
  cdci_data_analysis/analysis/parameters.py
  cdci_data_analysis/plugins/dummy_plugin/empty_instrument.py
  tests/test_job_management.py
  tests/test_parameters.py
  tests/test_server_basic.py
Labels: test-plugins, test-oda-api

#507 add limits to subclasses of numeric parameters
  cdci_data_analysis/analysis/parameters.py
Labels: test-plugins, test-oda-api

#508 inclusive bounds
  cdci_data_analysis/analysis/parameters.py
  cdci_data_analysis/analysis/products.py
Labels: test-plugins, test-oda-api

#509 multi-version-send-from-dir
  cdci_data_analysis/flask_app/dispatcher_query.py
Labels: bug, hotfix, test-plugins, test-oda-api

#511 invalid instr list
  cdci_data_analysis/flask_app/app.py
Labels: bug, hotfix, test-plugins, test-oda-api

#510 missing sentry dsn after url call fails and as arg to a number of calls
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/flask_app/app.py
Labels: product-gallery, test-plugins, test-oda-api

#514 adjusted sentry trace rate
  cdci_data_analysis/analysis/drupal_helper.py
  cdci_data_analysis/analysis/email_helper.py
  cdci_data_analysis/analysis/instrument.py
  cdci_data_analysis/analysis/products.py
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/flask_app/dispatcher_query.py
  cdci_data_analysis/flask_app/sentry.py
Labels: hotfix, test-plugins, test-oda-api

#516 new renku interactive
  cdci_data_analysis/analysis/renku_helper.py
Labels: hotfix, test-plugins, test-oda-api

#513 Fix redirection instr list
  .gitignore
  cdci_data_analysis/flask_app/app.py
  cdci_data_analysis/pytest_fixtures.py
  requirements.txt
  tests/conftest.py
  tests/test_server_basic.py
Labels: bug, test-plugins, test-oda-api

#518 missing library for setup
  setup.py
Labels: test-plugins, test-oda-api
